services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env
      - .env.prod
    ports:
      - "${PORT}:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    env_file:
      - .env
      - .env.prod
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: